<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>com.xtm.contract</groupId>
        <artifactId>tms-contract</artifactId>
        <version>20260204-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>tms-contract-server</artifactId>
    <description>tms-contract-server</description>

    <properties>
        <redisson.version>3.13.4</redisson.version>
        <maven.deploy.skip>true</maven.deploy.skip>
        <report.version>20250716-SNAPSHOT</report.version>
        <base-common.version>20250716-SNAPSHOT</base-common.version>
        <base-service.version>${base-common.version}</base-service.version>
        <base-datarule.version>${base-common.version}</base-datarule.version>
    </properties>
    <dependencies>
        <!--新服务依赖 ======================================================-->
        <!--分表相关配置-->
        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>shardingsphere-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>tms-contract-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>xtm-thirdparty-auth-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>tms-setting-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>tms-motorcade-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>tms-file-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>tms-integration-thirdparty-data-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>log-spring-boot-starter</artifactId>
        </dependency>


        <dependency>
            <groupId>com.yomahub</groupId>
            <artifactId>tlog-core</artifactId>
            <version>1.5.0</version>
        </dependency>
        <!-- 新服务依赖===================================================== -->
        <!-- 引入pdf -->
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itextpdf</artifactId>
            <version>5.4.2</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>2.3.26-incubating</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-freemarker</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
            <version>2.10.0</version>
        </dependency>

        <!--法大大sdk-->

        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>tms-company-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
        </dependency>

        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>mq-spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>tms-user-api</artifactId>
        </dependency>

        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>report-spring-boot-starter</artifactId>
        </dependency>

      <!-- MapStruct -->
      <dependency>
        <groupId>org.mapstruct</groupId>
        <artifactId>mapstruct</artifactId>
      </dependency>

      <dependency>
        <groupId>org.mapstruct</groupId>
        <artifactId>mapstruct-processor</artifactId>
        <scope>provided</scope>
      </dependency>

      <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok-mapstruct-binding</artifactId>
      </dependency>

      <dependency>
        <groupId>com.xtm</groupId>
        <artifactId>logistics-api</artifactId>
       </dependency>
      <dependency>
          <groupId>com.github.pagehelper</groupId>
          <artifactId>pagehelper-spring-boot-starter</artifactId>
          <version>1.4.3</version>
      </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <finalName>${project.parent.artifactId}</finalName>
    </build>

</project>
