<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xtm</groupId>
        <artifactId>xtm-parent</artifactId>
        <version>20260204-SNAPSHOT</version>
        <relativePath/>
    </parent>

    <!-- 202508080933 -->
    <description>TMS合同服务api</description>
    <name>${project.artifactId}</name>
    <artifactId>tms-contract-api</artifactId>
    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>base-api-common</artifactId>
        </dependency>

        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>loadbalancer-spring-boot-starter</artifactId>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <artifactId>base-common</artifactId>
                    <groupId>com.xtm</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.xtm</groupId>
            <artifactId>swagger2-spring-boot-starter</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
            <scope>provided</scope>
        </dependency>
      
      <!-- 兼容旧日志，序列化使用fastjson（不要再用fastjson了好不好） -->
      <dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>fastjson</artifactId>
      </dependency>
      
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>repackage</id>
                        <phase>package</phase>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                        <configuration>
                            <skip>true</skip>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
